name: dart_marganam
description: A commonly utilizable dart extension and utility package collection
publish_to: 'none'
version: 0.1.0
homepage: https://github.com/Terran-Source/dart-marganam-packages
repository: https://github.com/Terran-Source/dart-marganam-packages
issue_tracker: https://github.com/Terran-Source/dart-marganam-packages/issues

environment:
  sdk: '>=2.15.0 <3.0.0'
  flutter: '>=2.5.0'

dependencies:
  # crypto
  convert: ^3.0.1
  crypto: ^3.0.1

  # Functional programming
  dartz: ^0.10.1

  # drift-sqlite, previously moor-sqlite
  drift: ^1.1.0
  equatable: ^2.0.3
  extend: ^0.1.1

  flutter:
    sdk: flutter

  # http
  http: ^0.13.4

  interpolation: ^2.1.2

  # path libraries
  path: ^1.8.0
  path_provider: ^2.0.8

dev_dependencies:
  english_words: ^4.0.0
  flutter_test:
    sdk: flutter
  lint: ^1.8.1
  matcher: ^0.12.11
